force-app/main/default/objects/Catalog_Entry__mdt/Catalog_Entry__mdt.object-meta.xml
<CustomObject>
    <label>Catalog Entry</label>
    <pluralLabel>Catalog Entries</pluralLabel>
    <description>Metadata mapping Interfaces to Factories and Implementations</description>
</CustomObject>

force-app/main/default/objects/Catalog_Entry__mdt/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>Factory</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Catalog_Entry__mdt/fields/Interface__c.field-meta.xml
<CustomField>
    <fullName>Interface__c</fullName>
    <label>Interface</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Catalog_Entry__mdt/fields/Singleton__c.field-meta.xml
<CustomField>
    <fullName>Singleton__c</fullName>
    <label>Singleton</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/classes/CatalogEntry.cls
public with sharing class CatalogEntry {
    private Catalog_Entry__mdt entry;
    private IFactory factory_instance;
    private Object implementation_instance;

    public IFactory Factory {
        get {
            if(factory_instance == null) {
                factory_instance = 
                    (IFactory)Type.forName(entry.Factory__c)
                        .newInstance();
            }
            return factory_instance;
        }
    }

    public String EntryInterface {
        get {
            return entry.Interface__c;
        }
    }

    public Object implementation {
        get {
            if((entry.Singleton__c && implementation_instance == null) 
                || (!entry.Singleton__c)) {
                implementation_instance = Factory.buildObject();
            }
            return implementation_instance;
        }
    }
    
    public CatalogEntry(Catalog_Entry__mdt entry) {
        this.entry = entry;
    }
}