force-app/main/default/objects/Catalog_Entry__mdt/Catalog_Entry__mdt.object-meta.xml
<CustomObject>
    <label>Catalog Entry</label>
    <pluralLabel>Catalog Entries</pluralLabel>
    <description>Metadata mapping Interfaces to Factories and Implementations</description>
</CustomObject>

force-app/main/default/objects/Catalog_Entry__mdt/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>Factory</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Catalog_Entry__mdt/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <label>Implementation</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Catalog_Entry__mdt/fields/Interface__c.field-meta.xml
<CustomField>
    <fullName>Interface__c</fullName>
    <label>Interface</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Catalog_Entry__mdt/fields/Singleton__c.field-meta.xml
<CustomField>
    <fullName>Singleton__c</fullName>
    <label>Singleton</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/classes/Catalog.cls
public with sharing class Catalog {
    private List<CatalogEntry> entries;

    public Object getImplementation(String interfaceName) {
        if(entries == null) {
            loadEntries();
        }
        
        CatalogEntry entry = getImplementationCatalog(interfaceName);
        return entry.implementation;
    }

    private CatalogEntry getImplementationCatalog(String interfaceName) {
        for(CatalogEntry entry : entries) {
            if(entry.EntryInterface == interfaceName) {
                return entry;
            }
        }
        return null;
    }

    private void loadEntries() {
        if(entries == null) {
            entries = new List<CatalogEntry>();
            List<Catalog_Entry__mdt> catalog = [
                SELECT
                    Implementation__c,
                    Interface__c,
                    Factory__c,
                    Singleton__c
                FROM
                    Catalog_Entry__mdt
            ];
            for(Catalog_Entry__mdt entry : catalog) {
                entries.add(new CatalogEntry(entry));
            }
        }
    }

    private static Catalog instance;

    public static Catalog getInstance() {
        if (instance == null) {
            instance = new Catalog();
        }
        return instance;
    }
}